#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.
#
# Edited and improved by Jakob Niemeyer, May 2016
# Now supports two batteries and shows the mean value

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
# my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $bat_number = 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

# get data from the second battery
my $bat_number = 1;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# update values on expected output
if ($acpi =~ /: (\w+), (\d+)%/) {
	$percent = int( ($percent + $2 ) / 2 );
}

# format output
if($status eq 'Unknown') {
	$status = $1;
}
# the default text will be shown if both batteries are charged and the computer is running on direct AC
$full_text = "⚡";
if ($status eq 'Discharging') {
	if($percent < 10) {
		$full_text = "";
	} elsif ($percent < 28) {
		$full_text = "";
	} elsif ($percent < 53) {
		$full_text = "";
	} elsif ($percent < 78) {
		$full_text = "";
	} else {
		$full_text = "";
	}
} elsif ($status eq 'Charging') {
	$full_text = "";
}
$full_text .= " $percent%";

$short_text = $full_text;

#if ($acpi =~ /(\d\d:\d\d):/) {
#	$full_text .= " ($1)";
#}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#FF003C\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
