#!/bin/bash
# Copyright (C) 2016 Jakob Niemeyer 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
dateTime=$(date '+%a, %d.%m.  %H:%M')
echo "$dateTime" # full text
echo "$dateTime" # short text

#------------------------------------------------------------------------
# handle mouse clicks. piping to /dev/null prevents color changes

case $BLOCK_BUTTON in
  1) i3-msg exec gsimplecal > /dev/null 
     ;; #left click opens gui calender pop-up. see man gsimplecal for config options.
  3) i3-msg exec i3-sensible-terminal -e wyrd > /dev/null
     ;; #right click opens terminal with wyrd calender application
esac

